/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionRouteImport } from './routes/_collection'
import { Route as CollectionIndexRouteImport } from './routes/_collection/index'
import { Route as CollectionListsRouteImport } from './routes/_collection/lists'
import { Route as CollectionMembersIndexRouteImport } from './routes/_collection/members/index'
import { Route as CollectionMembersMemberIdRouteImport } from './routes/_collection/members/$memberId'

const CollectionRoute = CollectionRouteImport.update({
  id: '/_collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRoute,
} as any)
const CollectionListsRoute = CollectionListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => CollectionRoute,
} as any)
const CollectionMembersIndexRoute = CollectionMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => CollectionRoute,
} as any)
const CollectionMembersMemberIdRoute =
  CollectionMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => CollectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CollectionIndexRoute
  '/lists': typeof CollectionListsRoute
  '/members/$memberId': typeof CollectionMembersMemberIdRoute
  '/members/': typeof CollectionMembersIndexRoute
}
export interface FileRoutesByTo {
  '/lists': typeof CollectionListsRoute
  '/': typeof CollectionIndexRoute
  '/members/$memberId': typeof CollectionMembersMemberIdRoute
  '/members': typeof CollectionMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_collection': typeof CollectionRouteWithChildren
  '/_collection/lists': typeof CollectionListsRoute
  '/_collection/': typeof CollectionIndexRoute
  '/_collection/members/$memberId': typeof CollectionMembersMemberIdRoute
  '/_collection/members/': typeof CollectionMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lists' | '/members/$memberId' | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to: '/lists' | '/' | '/members/$memberId' | '/members'
  id:
    | '__root__'
    | '/_collection'
    | '/_collection/lists'
    | '/_collection/'
    | '/_collection/members/$memberId'
    | '/_collection/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CollectionRoute: typeof CollectionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_collection': {
      id: '/_collection'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_collection/': {
      id: '/_collection/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/_collection/lists': {
      id: '/_collection/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof CollectionListsRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/_collection/members/': {
      id: '/_collection/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof CollectionMembersIndexRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/_collection/members/$memberId': {
      id: '/_collection/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof CollectionMembersMemberIdRouteImport
      parentRoute: typeof CollectionRoute
    }
  }
}

interface CollectionRouteChildren {
  CollectionListsRoute: typeof CollectionListsRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  CollectionMembersMemberIdRoute: typeof CollectionMembersMemberIdRoute
  CollectionMembersIndexRoute: typeof CollectionMembersIndexRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionListsRoute: CollectionListsRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  CollectionMembersMemberIdRoute: CollectionMembersMemberIdRoute,
  CollectionMembersIndexRoute: CollectionMembersIndexRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CollectionRoute: CollectionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
